// Single source of truth for the HTTP contract shared by the web app and the
// iOS client (§11). The Swift mirror lives in
// `mobile/AIBOOSTER/Models/API.swift` — keep the two in sync by hand.
//
// The mobile client consumes EXISTING `/api/*` routes; no mobile-only
// endpoints. These types describe the exact JSON those routes return today
// (see app/api/jobs/route.ts, app/api/jobs/[id]/route.ts,
// app/api/translate-video/route.ts). Route handlers build the shapes from
// lib/jobs.ts; this file is the canonical reference for both sides.

import type {
  JobStatus,
  JobStage,
  WatchStatus,
  JobSource,
  JobSummary,
} from "./jobs";

export type { JobStatus, JobStage, WatchStatus, JobSource, JobSummary };

/** A chapter marker generated by the pipeline (stored as JSON, parsed on read). */
export interface Chapter {
  start_sec: number;
  title: string;
}

/** A transcript segment (~3 min chunk): original + translated text. */
export interface Segment {
  idx: number;
  start_ms: number;
  end_ms: number;
  source_text: string | null;
  translated_text: string | null;
}

/**
 * Full job as returned by `GET /api/jobs/[id]` under `job`. Note the field
 * names are normalized (url/video_id/title/duration_sec) vs the `yt_*` prefixed
 * columns surfaced by the list endpoint's JobSummary.
 */
export interface JobDetail {
  id: string;
  url: string;
  video_id: string;
  title: string | null;
  duration_sec: number | null;
  source_lang: string | null;
  target_lang: string;
  quality: string;
  status: JobStatus;
  stage: JobStage | null;
  progress: number;
  error_message: string | null;
  error_id: string | null;
  audio_url: string | null;
  watch_status: WatchStatus;
  last_position_sec: number;
  source: JobSource;
  summary: string | null;
  chapters: Chapter[];
  created_at: string;
  updated_at: string;
  finished_at: string | null;
}

// ---- Response / request envelopes ----

/** `GET /api/jobs?limit=N&watch=to_watch|watched|all` */
export interface JobsListResponse {
  jobs: JobSummary[];
}

/** `GET /api/jobs/[id]` */
export interface JobDetailResponse {
  job: JobDetail;
  segments: Segment[];
}

/** `POST /api/translate-video` body */
export interface CreateJobRequest {
  url: string;
  target_lang: string;
  quality?: "fast" | "best";
}

/** `POST /api/translate-video` success response */
export interface CreateJobResponse {
  job_id: string;
  cached: boolean;
}

/** `PATCH /api/jobs/[id]` body — at least one field required */
export interface PlaybackUpdateRequest {
  last_position_sec?: number;
  watch_status?: WatchStatus;
}

/** `PATCH /api/jobs/[id]` success response */
export interface OkResponse {
  ok: true;
}

/**
 * Error shape used by these job/video routes: FLAT `{ error, error_id? }`.
 * (Distinct from the §2 nested admin form `{ error: { code, message, error_id } }`.)
 */
export interface ApiErrorResponse {
  error: string;
  error_id?: string;
}

// =====================================================================
// News (Новости) — see app/api/news/*, lib/news-serialize.ts.
// All read/feedback routes are open. Serialized item shape comes from
// serializeItem() plus inline enrichment/related added by the route.
// =====================================================================

export type NewsKind = "telegram" | "rss" | "web";
export type NewsVerdict = "show" | "borderline" | "skip";
export type NewsEnrichStatus = "pending" | "running" | "done" | "failed";
export type NewsSignal = "like" | "dislike" | "hide";

export interface NewsSourceRef {
  id: string;
  name: string;
  kind: NewsKind;
  url: string;
}

export interface NewsImage {
  url: string;
  caption: string;
  source_url: string;
}

export interface NewsSourceUsed {
  url: string;
  title: string;
  role?: string;
  why_relevant: string;
}

/** Inline enrichment as returned under an item (and by /api/news/enrichment). */
export interface NewsEnrichmentView {
  status: NewsEnrichStatus;
  article_body: string | null;
  key_facts: string[];
  images: NewsImage[];
  sources_used: NewsSourceUsed[];
  original_source_url: string | null;
  model_used: string | null;
  cost_cents: number | null;
  latency_ms: number | null;
  completed_at: string | null;
  synthesis_error: string | null;
  synthesis_output_json?: string | null;
}

export interface RelatedNewsItem {
  id: string;
  title: string | null;
  url: string | null;
  source_name: string;
  published_at: string | null;
  relevance: number | null;
}

export interface NewsItem {
  id: string;
  source: NewsSourceRef;
  external_id: string;
  url: string | null;
  title: string | null;
  body: string | null;
  published_at: string | null;
  summary: string | null;
  value_explanation: string | null;
  matched_topics: string[];
  relevance: number | null;
  verdict: NewsVerdict | null;
  reasoning: string | null;
  model_used: string | null;
  validated_at: string | null;
  created_at: string;
  status: "pending" | "validated" | "failed";
  cluster_id: string | null;
  enrichment: NewsEnrichmentView | null;
  /** Only on the main feed; absent on read/skipped lists. */
  related?: RelatedNewsItem[];
  /** Only on the read list. */
  feedback_signal?: NewsSignal | null;
  feedback_at?: string;
}

/** GET /api/news/items, /api/news/items/read */
export interface NewsItemsResponse {
  count: number;
  items: NewsItem[];
}

/** GET /api/news/enrichment?item_id= */
export interface NewsEnrichmentResponse {
  enrichment: NewsEnrichmentView | null;
}

/** POST /api/news/feedback — marks the item read */
export interface NewsFeedbackRequest {
  item_id: string;
  signal: NewsSignal;
  reason_chip?: string;
  custom_text?: string;
}
