// Single source of truth for the HTTP contract shared by the web app and the
// iOS client (§11). The Swift mirror lives in
// `mobile/AIBOOSTER/Models/API.swift` — keep the two in sync by hand.
//
// The mobile client consumes EXISTING `/api/*` routes; no mobile-only
// endpoints. These types describe the exact JSON those routes return today
// (see app/api/jobs/route.ts, app/api/jobs/[id]/route.ts,
// app/api/translate-video/route.ts). Route handlers build the shapes from
// lib/jobs.ts; this file is the canonical reference for both sides.

import type {
  JobStatus,
  JobStage,
  WatchStatus,
  JobSource,
  JobSummary,
} from "./jobs";

export type { JobStatus, JobStage, WatchStatus, JobSource, JobSummary };

/** A chapter marker generated by the pipeline (stored as JSON, parsed on read). */
export interface Chapter {
  start_sec: number;
  title: string;
}

/** A transcript segment (~3 min chunk): original + translated text. */
export interface Segment {
  idx: number;
  start_ms: number;
  end_ms: number;
  source_text: string | null;
  translated_text: string | null;
}

/**
 * Full job as returned by `GET /api/jobs/[id]` under `job`. Note the field
 * names are normalized (url/video_id/title/duration_sec) vs the `yt_*` prefixed
 * columns surfaced by the list endpoint's JobSummary.
 */
export interface JobDetail {
  id: string;
  url: string;
  video_id: string;
  title: string | null;
  duration_sec: number | null;
  source_lang: string | null;
  target_lang: string;
  quality: string;
  status: JobStatus;
  stage: JobStage | null;
  progress: number;
  error_message: string | null;
  error_id: string | null;
  audio_url: string | null;
  watch_status: WatchStatus;
  last_position_sec: number;
  source: JobSource;
  summary: string | null;
  chapters: Chapter[];
  created_at: string;
  updated_at: string;
  finished_at: string | null;
}

// ---- Response / request envelopes ----

/** `GET /api/jobs?limit=N&watch=to_watch|watched|all` */
export interface JobsListResponse {
  jobs: JobSummary[];
}

/** `GET /api/jobs/[id]` */
export interface JobDetailResponse {
  job: JobDetail;
  segments: Segment[];
}

/** `POST /api/translate-video` body */
export interface CreateJobRequest {
  url: string;
  target_lang: string;
  quality?: "fast" | "best";
}

/** `POST /api/translate-video` success response */
export interface CreateJobResponse {
  job_id: string;
  cached: boolean;
}

/** `PATCH /api/jobs/[id]` body — at least one field required */
export interface PlaybackUpdateRequest {
  last_position_sec?: number;
  watch_status?: WatchStatus;
}

/** `PATCH /api/jobs/[id]` success response */
export interface OkResponse {
  ok: true;
}

/**
 * Error shape used by these job/video routes: FLAT `{ error, error_id? }`.
 * (Distinct from the §2 nested admin form `{ error: { code, message, error_id } }`.)
 */
export interface ApiErrorResponse {
  error: string;
  error_id?: string;
}
